apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:  
  name: {{ .Chart.Name }}-{{ .Release.Name }}-hpa-back
  namespace: wicem-ns  
spec:
  maxReplicas: {{ .Values.spechpa.max }}
  minReplicas: {{ .Values.spechpa.min}}
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: {{ .Chart.Name }}-{{ .Release.Name }}-back
  targetCPUUtilizationPercentage: {{ .Values.spechpa.targetCPU }}