apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}-postgres-login
type: Opaque
data:
  user: {{ .Values.secrets.data.user }}
  password: {{ .Values.secrets.data.password }}
  uri: {{ .Values.secrets.data.uri }}
  port: {{ .Values.secrets.data.port }}
  database: {{ .Values.secrets.data.database }}