apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}
spec:
  selector:
    role: {{ .Values.back.labels.role}}
    {{ .Values.back.labels.else.key | nindent 4 }}: {{ .Values.back.labels.else.value }}
  ports:
  - protocol:
    port: {{ .Values.service.port }}
    targetPort: 5000
  type: {{ .Values.service.type }}
