apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}-svc-front
spec:
  selector:
    role: {{ .Values.front.labels.role}}
    {{ .Values.front.labels.else.key | nindent 4 }}: {{ .Values.front.labels.else.value }}
  ports:
  - protocol:
    port: {{ .Values.service.port }}
    targetPort: 80
  type: {{ .Values.service.type }}


