apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:  
  name: wicemchart-wicemhelm-front
  namespace: wicem-ns  
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: wicemchart-wicemhelm-front
  targetCPUUtilizationPercentage: 5
